import { FormaPagoInterface } from "../interfaces/forma-pago.interface";

export const formas:FormaPagoInterface[] = [
    {
        "tipo_Cargo_Abono": 5,
        "descripcion": "EFECTIVO*",
        "monto": true,
        "referencia": false,
        "autorizacion": false,
        "calcular_Monto": true,
        "cuenta_Corriente": false,
        "reservacion": false,
        "facturar": false,
        "efectivo": true,
        "banco": false,
        "fecha_Vencimiento": false,
        "comision_Porcentaje": 0.00,
        "comision_Monto": 0.00,
        "contabilizar": false,
        "val_Limite_Credito": false,
        "msg_Limite_Credito": false,
        "bloquear_Documento": true,
        "url": "../Image/TCA/Cash-48.png"
    },
    {
        "tipo_Cargo_Abono": 34,
        "descripcion": "AMERICAN EXPRESS*",
        "monto": true,
        "referencia": true,
        "autorizacion": true,
        "calcular_Monto": true,
        "cuenta_Corriente": false,
        "reservacion": false,
        "facturar": false,
        "efectivo": false,
        "banco": false,
        "fecha_Vencimiento": false,
        "comision_Porcentaje": 7.00,
        "comision_Monto": 0.00,
        "contabilizar": false,
        "val_Limite_Credito": false,
        "msg_Limite_Credito": false,
        "bloquear_Documento": false,
        "url": "../Image/TCA/american-express-48.png"
    },
    {
        "tipo_Cargo_Abono": 8,
        "descripcion": "CHEQUE *",
        "monto": true,
        "referencia": true,
        "autorizacion": false,
        "calcular_Monto": true,
        "cuenta_Corriente": false,
        "reservacion": false,
        "facturar": false,
        "efectivo": false,
        "banco": true,
        "fecha_Vencimiento": false,
        "comision_Porcentaje": 0.00,
        "comision_Monto": 0.00,
        "contabilizar": false,
        "val_Limite_Credito": false,
        "msg_Limite_Credito": false,
        "bloquear_Documento": true,
        "url": "../Image/TCA/Check-48.png"
    },
    {
        "tipo_Cargo_Abono": 33,
        "descripcion": "DEPOSITO*",
        "monto": true,
        "referencia": true,
        "autorizacion": false,
        "calcular_Monto": true,
        "cuenta_Corriente": false,
        "reservacion": false,
        "facturar": false,
        "efectivo": true,
        "banco": true,
        "fecha_Vencimiento": false,
        "comision_Porcentaje": 0.00,
        "comision_Monto": 0.00,
        "contabilizar": false,
        "val_Limite_Credito": false,
        "msg_Limite_Credito": false,
        "bloquear_Documento": false,
        "url": "../Image/TCA/Cash-48.png",
        "req_Cuenta_Bancaria": true
    },
    {
        "tipo_Cargo_Abono": 14,
        "descripcion": "MASTERCARD *",
        "monto": true,
        "referencia": true,
        "autorizacion": true,
        "calcular_Monto": true,
        "cuenta_Corriente": false,
        "reservacion": false,
        "facturar": false,
        "efectivo": false,
        "banco": false,
        "fecha_Vencimiento": false,
        "comision_Porcentaje": 7.00,
        "comision_Monto": 0.00,
        "contabilizar": false,
        "val_Limite_Credito": false,
        "msg_Limite_Credito": false,
        "bloquear_Documento": false,
        "url": "../Image/TCA/Mastercard-48.png"
    }
];